#!/usr/bin/env bash
 
# ./run init production
# ./run plan production
# ./run apply production

TF_ENV=$2
TF_ACTION=$1
 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
# Always run from the location of this script
cd $DIR
 
if [ $# -gt 0 ]; then
    if [ "$TF_ACTION" == "init" ]; then
        terraform -chdir=./$TF_ENV init -backend-config=../$TF_ENV-backend.tf -var-file=../$TF_ENV-variables.tfvars
    else
        terraform -chdir=./$TF_ENV $TF_ACTION -var-file=../$TF_ENV-variables.tf
    fi
fi

cd -